# Generated by Django 4.0.4 on 2022-05-24 14:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jumla', '0002_alter_bill_date_alter_cart_date_alter_product_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 14, 58, 16, 1509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 14, 58, 16, 1509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 14, 58, 16, 1509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopOwner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopOwner', to=settings.AUTH_USER_MODEL),
        ),
    ]
