# Generated by Django 4.0.4 on 2022-05-27 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jumla', '0005_alter_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
