# Generated by Django 4.0.4 on 2022-05-29 21:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jumla', '0006_alter_product_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Governorate',
        ),
        migrations.AlterField(
            model_name='bill',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Cart_Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_Governorate', to='jumla.governorate')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_id', to='jumla.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to='jumla.product')),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='products',
            field=models.ManyToManyField(related_name='bill_products', to='jumla.bill_items'),
        ),
    ]
