# Generated by Django 4.0.4 on 2022-05-31 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumla', '0008_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
