# Generated by Django 4.0.4 on 2022-05-31 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumla', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
