# Generated by Django 4.0.4 on 2022-06-05 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jumla', '0010_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Image_Product', to='jumla.product')),
            ],
            options={
                'verbose_name': 'product_Image',
                'verbose_name_plural': 'product_Images',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='checkout',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category/'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='jumla.category', verbose_name='parent'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
