# Generated by Django 4.0.4 on 2022-06-07 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jumla', '0011_product_images_cart_checkout_cart_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_city', to='jumla.governorate'),
        ),
        migrations.DeleteModel(
            name='Cart_Governorate',
        ),
    ]
