# Generated by Django 4.0.4 on 2022-06-07 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumla', '0012_cart_city_delete_cart_governorate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Available',
            new_name='is_active',
        ),
    ]
