# Generated by Django 4.0.4 on 2022-06-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumla', '0013_alter_bill_products_alter_user_groups_and_more'),
        ('jumla', '0015_alter_bill_items_item'),
    ]

    operations = [
    ]
