# Generated by Django 4.0 on 2022-06-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumla', '0016_merge_20220615_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'الفئات'},
        ),
        migrations.AlterModelOptions(
            name='governorate',
            options={'verbose_name': 'المحافظة', 'verbose_name_plural': 'المحافظات'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
