# Generated by Django 4.0 on 2022-07-09 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumla', '0018_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
