# Generated by Django 4.0 on 2022-07-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumla', '0020_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
        migrations.DeleteModel(
            name='room',
        ),
    ]
